Changed strain_seed_value to strain_seed_rate
mrc-ide/sircovid pull request #252
Opened 2021-03-19 12:18 UTC by RaphaelS1

* `strain_seed_value` set daily seeding to new strain, now `strain_seed_rate` simulated from Poisson(strain_seed_rate). Rate is again divided equally over steps
* https://github.com/mrc-ide/sircovid/issues/245 (point 5)
* all tests pass except "calculate Rt with both second variant and vaccination" in test-carehomes-multistrain.R which fails the second test in the first particle (even when changing seeds) unless tolerance set to 0.2. Unsure if this is expected or a bug

2021-03-22 15:01 UTC, annecori requested changes
All looks good except minor comment on documentation. Eventually we may want to change the dates of seeding so you only have to specify one date per rate, in the same way we have the beta_values and beta_dates specified, but we should discuss and this can be done in a separate PR I think

2021-03-24 18:12 UTC, richfitz commented
I've put a fix for the GPU compilation on 9c1553f, which uses https://github.com/mrc-ide/dust/pull/223; once that version of dust is merged the branch pin can be removed but as this does not affect anything for you you can merge this PR before the dust one is merged

2021-03-25 11:54 UTC, annecori requested changes

2021-03-25 11:54 UTC, annecori commented on R/carehomes.R
> -    assert_integer(strain_seed_value)
we should probably replace this by a check that the values in there are all positive?

2021-03-25 11:54 UTC, annecori commented on R/carehomes.R
> -    assert_integer(strain_seed_value)
and add corresponding tests

2021-03-25 11:54 UTC, annecori commented on tests/testthat/test-carehomes-multistrain.R
> +test_that("Can seed with two-day window", {
should this say 10-day?

2021-03-25 11:54 UTC, annecori commented on tests/testthat/test-carehomes-multistrain.R
> +test_that("Can seed with > two-day window", {
suggest changing to: "can seed with > 2 dates"

2021-03-25 11:54 UTC, annecori commented on tests/testthat/test-carehomes-multistrain.R
> +                              sircovid_date(c(date_seeding, date_seeding)) +
could write more simply as c(date_seeding, date_seeding + 1)?

2021-03-25 11:54 UTC, annecori commented on tests/testthat/test-carehomes-multistrain.R
> +                              sircovid_date(c(date_seeding, date_seeding)) +
same as above

2021-03-25 11:54 UTC, annecori commented on tests/testthat/test-carehomes-multistrain.R
> +                              sircovid_date(c(date_seeding, date_seeding)) +
again

2021-03-25 12:55 UTC, annecori approved these changes

2021-03-25 12:56 UTC, merged