added logical flags for state variable outputs
mrc-ide/sircovid pull request #388
Opened 2022-01-11 17:36 UTC by epiyasin

2022-01-12 22:36 UTC, edknock commented on R/lancelot.R
> +##' @param rt logical parameter output trajectories required for
```suggestion
##' @param rt Logical, whether to output trajectories required for
```

2022-01-12 22:36 UTC, edknock commented on R/lancelot.R
> +##' @param cum_admit logical parameter whether to output cumulative
```suggestion
##' @param cum_admit Logical, whether to output cumulative
```

2022-01-12 22:37 UTC, edknock commented on R/lancelot.R
> +##' @param diagnoses_admitted logical parameter whether to output
****
```suggestion
##' @param diagnoses_admitted Logical, whether to output
```

2022-01-12 22:37 UTC, edknock commented on R/lancelot.R
> +##' @param cum_infections_disag logical parameter whether to output
```suggestion
##' @param cum_infections_disag Logical, whether to output
```

2022-01-12 22:38 UTC, edknock commented on R/lancelot.R
> +##' @param cum_n_vaccinated logical parameter whether to output
```suggestion
##' @param cum_n_vaccinated Logical, whether to output
```

2022-01-13 10:55 UTC, epiyasin commented
codecov failing due to pre-existing miss on master

2022-01-14 16:10 UTC, edknock commented on tests/testthat/test-lancelot-pmcmc.R
> +test_that("Can drop predictions from trajectories", {
Remove this test and the next 4 as they've been deleted from master (they are testing functions that have been deleted)

2022-02-02 08:44 UTC, richfitz requested changes
I'd like you to back out some of the changes that were made to the tests but appear no longer needed.  You can do this by running

```
git fetch
git merge origin/fit_index-function-patch
```

or by working through the comments I've left below

2022-02-02 08:44 UTC, richfitz commented on tests/testthat/helper-lancelot-pmcmc.R
> +    incidence <- "icu"
I believe these changes can be reverted - can you please check

2022-02-02 08:44 UTC, richfitz commented on tests/testthat/helper-lancelot.R
> +  fit_index <- function(info) {
I believe these changes can be reverted

2022-02-02 08:44 UTC, richfitz commented on tests/testthat/test-lancelot-pmcmc.R
> +  v <- c("general", "icu")
I believe these can be reverted

2022-02-02 12:43 UTC, richfitz approved these changes

2022-02-02 12:45 UTC, richfitz commented
buildkite build taking its time due to slow archive downloading, will pass eventually

2022-02-02 12:46 UTC, merged